title: TSaMP
paginate: 5
theme: PaperMod

buildFuture: false
buildExpired: false
enableInlineShortcodes: true
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  title: TSaMP
  description: "I'm a fool :)"
  keywords: [Blog, Experiment, Foolishness, Journal]
  author: Donald E. Quixote
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  label:
    text: To Solve a Millennium Problem

  assets:
    favicon: "/icons/favicon.png"
    favicon16x16: "/icons/favicon.png"
    favicon32x32: "/icons/favicon.png"

  # home-info mode
  homeInfoParams:
    Title: "You're about to witness History"
    Content: | 
      - I have a great plan.
      - Step 1: Choose a Millennium Problem.
      - Step 2: Solve the Millennium Problem.
      - Step 3: Profit.
      -
      - If this confuses you, check the [**About**](about) section.
      - It should enlight you on my genius plan.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/deq_not_qed"
    - name: github
      url: "https://github.com/maxhr-0x90"
    - name: email
      url: "mailto://deq.not.qed@gmail.com"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/maxhr-0x90/TSaMP-Hugo/blob/main/content"
    Text: "Something's fucky" # edit text
    appendFilePath: true # to append file path to Edit link

  math: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: hub
      name: Hub
      url: /posts/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 50
    - identifier: glossary
      name: Glossary
      url: https://en.wikipedia.org/wiki/Glossary_of_mathematical_symbols
      weight: 60
    
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    style: monokai
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
